# Generated by Django 3.0.3 on 2020-02-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_empresa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trabajando', 'Trabajando'), ('desempleado', 'Desempleado'), ('ingresado', 'Ingresado')], default='desempleado', max_length=30, verbose_name='Estado De La Persona')),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido_1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre_1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupacion Actual')),
                ('cargo_opt', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo a Optar')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telf', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('ninguno', 'Prefiero No Contestar')], max_length=50, null=True)),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Empresa', verbose_name='Codigo Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('cod_familia', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido_1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre_1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Persona')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('cod_educ', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo Obtenido')),
                ('finalizado', models.BooleanField()),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Fecha De Inicio Del Curso')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha De Obtencion Del Titulo')),
                ('aptitudes', models.CharField(max_length=50, verbose_name='Aptitud o Habilidad Obtenida')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Persona')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Educacion',
            },
        ),
    ]
