# Generated by Django 3.0.3 on 2020-02-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='empresa',
            name='ceo',
            field=models.CharField(default='1', max_length=50, verbose_name='Fundador de la Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='emp',
            field=models.PositiveIntegerField(default='1', verbose_name='Cantidad De Empleados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='prop',
            field=models.TextField(default='1', verbose_name='Proposito de la Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='rif',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_creacion',
            field=models.DateField(verbose_name='Fecha De Creacion De Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de la Empresa'),
        ),
    ]
