# Generated by Django 3.0.3 on 2020-02-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_auto_20200215_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Persona Summary',
                'verbose_name_plural': 'Personas Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recursos_humanos.persona',),
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Solicitud De Ingreso', 'verbose_name_plural': 'Solicitudes De Ingresos'},
        ),
        migrations.AddField(
            model_name='persona',
            name='fech_ing',
            field=models.DateField(auto_now=True),
        ),
    ]
