# Generated by Django 3.0.3 on 2020-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_auto_20200215_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/empleados'),
        ),
    ]
