# Generated by Django 3.0.3 on 2020-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_auto_20200222_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='porct',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sueldo Porcentaje'),
        ),
    ]
