# Generated by Django 3.0.3 on 2020-02-22 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0007_escala_porct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['cod_empresa', 'escala'], 'verbose_name': 'Escala de Sueldo', 'verbose_name_plural': 'Escala de Sueldos'},
        ),
        migrations.AlterField(
            model_name='escala',
            name='porct',
            field=models.BooleanField(blank=True, null=True, verbose_name='Porcentaje'),
        ),
        migrations.AlterUniqueTogether(
            name='escala',
            unique_together={('cod_empresa', 'escala', 'grado', 'paso')},
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_departamento', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Del Departamento')),
                ('descripcion', models.CharField(max_length=50, null=True, verbose_name='Descripcion')),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Empresa', verbose_name='Codigo De La Empresa')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['cod_empresa', 'descripcion'],
            },
        ),
    ]
