# Generated by Django 3.0.3 on 2020-02-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0008_auto_20200222_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='cod_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_cargo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Del Cargo')),
                ('des_cargo', models.CharField(max_length=50, null=True, verbose_name='Descripcion Del Cargo')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Sueldo Base')),
                ('insuel', models.BooleanField(blank=True, default=0, null=True, verbose_name='Utilizar Sueldo Escala')),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Empresa', verbose_name='Codigo De La Empresa')),
                ('cod_escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Escala', verbose_name='Codigo Escala')),
            ],
        ),
    ]
