# Generated by Django 3.0.3 on 2020-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0010_auto_20200222_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del Cargo'),
        ),
    ]
