# Generated by Django 3.0.3 on 2020-02-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_auto_20200222_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='insuel',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='Utilizar Sueldo Escala'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Sueldo Base'),
        ),
    ]
