# Generated by Django 3.0.3 on 2020-02-23 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_auto_20200222_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['cod_empresa', 'cargo'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterField(
            model_name='escala',
            name='porct',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Porcentaje'),
        ),
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('cod_rac', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Puesto')),
                ('compensacion', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cod_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Cargo', verbose_name='Cargo')),
                ('cod_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Departamento', verbose_name='Departamento')),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Empresa', verbose_name='Codigo De La Empresa')),
                ('cod_escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Escala')),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajos',
                'ordering': ['cod_empresa', 'cod_rac'],
            },
        ),
    ]
