# Generated by Django 3.0.3 on 2020-02-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0013_auto_20200222_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telf',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono'),
        ),
    ]
