# Generated by Django 3.0.3 on 2020-02-23 13:27

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0014_auto_20200222_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True),
        ),
    ]
