# Generated by Django 3.0.3 on 2020-02-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0015_persona_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='phone',
        ),
    ]
