# Generated by Django 3.0.3 on 2020-02-23 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0016_remove_persona_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rac',
            name='cod_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Persona', verbose_name='Solicitud Empleado'),
        ),
        migrations.AlterField(
            model_name='rac',
            name='cod_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Empresa', verbose_name='Empresa'),
        ),
    ]
