# Generated by Django 3.0.3 on 2020-02-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0017_auto_20200223_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rac',
            name='cod_solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Persona', verbose_name='Solicitud Empleado'),
        ),
    ]
