# Generated by Django 3.0.3 on 2020-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0019_educacionempleado_empleado_familiaempleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cargo_opt',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='cod_solicitud',
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
    ]
