# Generated by Django 3.0.3 on 2020-02-23 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0020_auto_20200223_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacionempleado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Empleado'),
        ),
        migrations.AlterField(
            model_name='familiaempleado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.Empleado'),
        ),
    ]
