# Generated by Django 3.0.3 on 2020-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0021_auto_20200223_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sueldo',
            field=models.FloatField(blank=True, null=True, verbose_name='Sueldo Empleado'),
        ),
    ]
