# Generated by Django 3.0.3 on 2020-02-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0022_auto_20200223_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ocupacion',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
