# Generated by Django 3.0.3 on 2020-02-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0023_auto_20200223_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rac',
            name='cod_solicitud',
        ),
    ]
