# Generated by Django 3.0.3 on 2020-02-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0024_remove_rac_cod_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cod_solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.Persona', verbose_name='Solicitud Empleado'),
        ),
    ]
