# Generated by Django 3.0.3 on 2020-02-15 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_cargo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Del Cargo')),
                ('des_cargo', models.CharField(max_length=50, null=True, verbose_name='Descripcion Del Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_departamento', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Del Departamento')),
                ('descripcion', models.CharField(max_length=50, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoPago2',
            fields=[
                ('cod_elemento_pago', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=20)),
                ('codigo_ad', models.CharField(choices=[('asignacion', 'Asignacion'), ('deduccion', 'Deduccion'), ('prestamo', 'Prestamo')], default='asignacion', max_length=30)),
                ('formula', models.CharField(blank=True, max_length=250, null=True, verbose_name='Formula o Monto')),
                ('frecuencia', models.CharField(blank=True, choices=[('td', 'Todas las Quincenas'), ('fm', 'Final de Mes')], default='td', max_length=30, null=True)),
                ('codigo_cp', models.CharField(blank=True, choices=[('fijo', 'Fijo'), ('variable', 'Variable'), ('fijoingreso', 'Fijo De Ingreso')], default='variable', max_length=30, null=True)),
                ('control', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Elemento de Pago',
                'verbose_name_plural': 'Elementos de Pago',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod_empleado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('sueldo', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('cod_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Cargo')),
                ('cod_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cod_empresa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_update', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('cod_escala', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo De Escala')),
                ('escala', models.CharField(max_length=20, verbose_name='Nombre Escala')),
                ('grado', models.IntegerField(verbose_name='Grado')),
                ('paso', models.IntegerField(verbose_name='Paso')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Sueldo')),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa', verbose_name='Codigo De La Empresa')),
            ],
            options={
                'ordering': ['escala'],
                'unique_together': {('escala', 'grado', 'paso')},
            },
        ),
        migrations.CreateModel(
            name='PagoEmpleado2',
            fields=[
                ('cod_pago', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField(blank=True, default='1', null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=20, null=True)),
                ('formula', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.Empleado')),
                ('elemento_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema.ElementoPago2')),
            ],
            options={
                'verbose_name': 'Pago de Empleado',
                'verbose_name_plural': 'Pagos de los Empleados',
                'ordering': ('cod_empleado',),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cod_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trabajando', 'Trabajando'), ('desempleado', 'Desempleado'), ('ingresado', 'Ingresado')], default='desempleado', max_length=30, verbose_name='Estado De La Persona')),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido_1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre_1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupacion Actual')),
                ('cargo_opt', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo a Optar')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telf', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('ninguno', 'Prefiero No Contestar')], max_length=50, null=True)),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa', verbose_name='Codigo Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ingreso Del Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('cod_variable', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('cod_rac', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo RAC')),
                ('compensacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cod_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Cargo', verbose_name='Codigo Del Cargo')),
                ('cod_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Departamento', verbose_name='Codigo Del Departamento')),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa', verbose_name='Codigo De La Empresa')),
                ('cod_escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Escala')),
                ('cod_solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Persona', verbose_name='Codigo De Solicitud Empleado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prenomina',
            fields=[
                ('cod_prenomina', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('obreros', 'Obreros'), ('trabajadores', 'Trabajadores'), ('ejecutivo', 'Ejecutivo')], default='trabajadores', max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('pagos_empleados', models.ManyToManyField(to='sistema.PagoEmpleado2')),
            ],
        ),
        migrations.CreateModel(
            name='Formulacion',
            fields=[
                ('cod_formula', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('formula', models.CharField(max_length=250)),
                ('descripcion', models.CharField(default='prueba', max_length=250)),
                ('cod_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa')),
            ],
            options={
                'verbose_name': 'Formulacion',
                'verbose_name_plural': 'Formulaciones',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('cod_familia', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido_1', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre_1', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('nombre_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Persona')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='cod_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cod_rac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Rac'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cod_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Solicitud_Empleado', to='sistema.Persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementopago2',
            name='cod_formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Formulacion'),
        ),
        migrations.AddField(
            model_name='elementopago2',
            name='empleado_pago',
            field=models.ManyToManyField(through='sistema.PagoEmpleado2', to='sistema.Empleado'),
        ),
        migrations.AddField(
            model_name='elementopago2',
            name='pago',
            field=models.ManyToManyField(through='sistema.PagoEmpleado2', to='sistema.ElementoPago2'),
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('cod_educ', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo Obtenido')),
                ('finalizado', models.BooleanField()),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='Fecha De Obtencion de Titulo')),
                ('aptitudes', models.CharField(max_length=50, verbose_name='Aptitud o Habilidad Obtenida')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Persona')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Educacion',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='cod_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa', verbose_name='Codigo De La Empresa'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cod_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Empresa', verbose_name='Codigo De La Empresa'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cod_escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.Escala', verbose_name='Codigo Escala'),
        ),
    ]
