# Generated by Django 3.0.3 on 2020-02-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha De Obtencion Del Titulo'),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha De Inicio Del Curso'),
        ),
    ]
