# Generated by Django 3.0.3 on 2020-02-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20200215_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Departamento'),
        ),
    ]
